### ISSUE TITLE
[토, 일] 질문 추가 day

### ISSUE THREAD

**Issue by KSH-code** [KSH-code/Technical-Interview#2]
기억에서 사라지기 전에 메모하는 용도
## CS
- [x] I/O bound, CPU bound
- [ ] 프로세스와 쓰레드의 차이
- [ ] TCP/IP
- [ ] HTTP
- [ ] HTTP 와 다른 SMTP 같은 프로토콜과의 차이점
- [ ] HTTP 와 HTTPS 프로토콜 차이점
## Hash
- [x] Hash table
- [x] Hashing 등등
## tree
- [ ] Balanced Tree
- [ ] Trie
## select
- [ ] quick select
## heap
- [x] heap
## other
- [ ] REST API 란
- [x] What is an index in database
- [x] How to fix high CPU usage in rest API server

**Comment by KSH-code** [comment]
프로세스 스레드 차이
https://magi82.github.io/process-thread/
https://brunch.co.kr/@kd4/3

**Comment by KSH-code** [comment]
개인적인 사정으로 인해서
11/07 에 많이 올릴게요.

**Comment by KimGenius** [comment]
11월 7일이 지난지 거의 2달이 되어갑니다...

**Comment by KSH-code** [comment]
내일부터 다시 올릴게요 ㅎㅎ

**Comment by KSH-code** [comment]
- [ ] 페이지네이션 할 때, 데이터 빨리 불러오는 방법

**Comment by KimGenius** [comment]
이슈에 글만 올리고 실제로 수정은 안하시네요.;

**Comment by KSH-code** [comment]
> 이슈에 글만 올리고 실제로 수정은 안하시네요.;

이미 여러 번 커밋을 했습니다.
확인 부탁드려요.

**Comment by KimGenius** [comment]
여러 번은 아니고 한번이네요.
확인 부탁드려요.
